# Generated by Django 5.2.3 on 2025-07-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_updatebanner3'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrishclubGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/irishclub/images/')),
            ],
        ),
    ]
