# Generated by Django 5.2.3 on 2025-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_collection3'),
    ]

    operations = [
        migrations.CreateModel(
            name='JackmillerGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/jackmiller/images/')),
            ],
        ),
    ]
