# Generated by Django 5.1.2 on 2025-07-11 18:52

import store.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_contacthero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/product_hero/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/product_hero/videos/', validators=[store.utils.validators.validate_video_file_extension])),
            ],
        ),
    ]
