# Generated by Django 5.1.2 on 2025-07-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Collection',
            new_name='collection',
        ),
    ]
