# Generated by Django 5.2.3 on 2025-07-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_category_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Collections',
        ),
    ]
