# Generated by Django 5.2.3 on 2025-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/brand_banner/'),
        ),
    ]
