# Generated by Django 5.2.3 on 2025-07-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/district_11/images/')),
            ],
        ),
    ]
