# Generated by Django 5.2.3 on 2025-07-12 19:34

import store.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_collection4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description1', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/store/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/store/videos/', validators=[store.utils.validators.validate_video_file_extension])),
            ],
        ),
    ]
