# Generated by Django 5.2.3 on 2025-07-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description1',
        ),
    ]
