# Generated by Django 5.2.3 on 2025-07-13 15:26

import store.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_store_description1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/collab_hero/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/collab_hero/videos/', validators=[store.utils.validators.validate_video_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='StoreHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/store_hero/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/store_hero/videos/', validators=[store.utils.validators.validate_video_file_extension])),
            ],
        ),
    ]
