# Generated by Django 5.2.3 on 2025-07-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_collabhero_storehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=200, null=True)),
                ('description1', models.TextField(blank=True, max_length=1000, null=True)),
                ('image1', models.ImageField(upload_to='uploads/collab/')),
                ('image2', models.ImageField(upload_to='uploads/collab/')),
                ('image3', models.ImageField(upload_to='uploads/collab/')),
                ('image4', models.ImageField(upload_to='uploads/collab/')),
                ('image5', models.ImageField(upload_to='uploads/collab/')),
            ],
        ),
    ]
