# Generated by Django 5.2.3 on 2025-07-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_collab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='collab',
            name='image5',
        ),
        migrations.AddField(
            model_name='collab',
            name='collab_banner',
            field=models.FileField(blank=True, null=True, upload_to='uploads/collab/banner/'),
        ),
    ]
