# Generated by Django 5.1.2 on 2025-07-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_collab_image4_remove_collab_image5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='collab_banner',
        ),
        migrations.AddField(
            model_name='collab',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
        migrations.AddField(
            model_name='collab',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
        migrations.AddField(
            model_name='collab',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
        migrations.AddField(
            model_name='collab',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
        migrations.AddField(
            model_name='collab',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
        migrations.AddField(
            model_name='collab',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
        migrations.AddField(
            model_name='collab',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/collab/'),
        ),
    ]
