# Generated by Django 5.1.2 on 2025-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_collab_collab_banner_collab_image10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouthero',
            options={'verbose_name': '**About Us - Hero Image (About Us Page)', 'verbose_name_plural': '**About Us - Hero Image (About Us Page)'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Our Brands (Add Your Brands Here)', 'verbose_name_plural': 'Our Brands (Add Your Brands Here)'},
        ),
        migrations.AlterModelOptions(
            name='brandbanner',
            options={'verbose_name': 'Our Brands Display - Background Banner (Home Page)', 'verbose_name_plural': 'Our Brands Display - Background Banner (Home Page)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category (Add Categories Here)', 'verbose_name_plural': 'Categories (Add Categories Here)'},
        ),
        migrations.AlterModelOptions(
            name='collab',
            options={'verbose_name': 'Collaborations Media (Add up to 10 images for each collaboration)', 'verbose_name_plural': 'Collaborations Media (Add up to 10 images for each collaboration)'},
        ),
        migrations.AlterModelOptions(
            name='collabhero',
            options={'verbose_name': '**Collaborations - Hero Image (Collaborations Page)', 'verbose_name_plural': '**Collaborations - Hero Image (Collaborations Page)'},
        ),
        migrations.AlterModelOptions(
            name='collection1',
            options={'verbose_name': 'Collection Layer 1 : Home Screen (Add a Collection Here)', 'verbose_name_plural': 'Collection Layer 1 : Home Screen (Add a Collection Here)'},
        ),
        migrations.AlterModelOptions(
            name='collection2',
            options={'verbose_name': 'Collection Layer 2 : Home Screen (Add a Collection Here)', 'verbose_name_plural': 'Collection Layer 2 : Home Screen (Add a Collection Here)'},
        ),
        migrations.AlterModelOptions(
            name='collection3',
            options={'verbose_name': 'Collection Layer 3 : Home Screen (Add a Collection Here)', 'verbose_name_plural': 'Collection Layer 3 : Home Screen (Add a Collection Here)'},
        ),
        migrations.AlterModelOptions(
            name='collection4',
            options={'verbose_name': 'Collection Layer 4 : Home Screen (Add a Collection Here)', 'verbose_name_plural': 'Collection Layer 4 : Home Screen (Add a Collection Here)'},
        ),
        migrations.AlterModelOptions(
            name='collections',
            options={'verbose_name': 'Collection (Add Your Collections Here)', 'verbose_name_plural': 'Collections (Add Your Collections Here)'},
        ),
        migrations.AlterModelOptions(
            name='contacthero',
            options={'verbose_name': '**Contact Us - Hero Image (Contact Us Page)', 'verbose_name_plural': '**Contact Us - Hero Image (Contact Us Page)'},
        ),
        migrations.AlterModelOptions(
            name='districtgrid',
            options={'verbose_name': '**New in District 11 : Home Page (Add up to 6 Images of Products in District 11 Here)', 'verbose_name_plural': '**New in District 11 : Home Page (Add up to 6 Images of Products in District 11 Here)'},
        ),
        migrations.AlterModelOptions(
            name='gallygrid',
            options={'verbose_name': '**New in Gally : Home Page (Add up to 6 Images of Products in Gally Here)', 'verbose_name_plural': '**New in Gally : Home Page (Add up to 6 Images of Products in Gally Here)'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero Banner (Home Page)', 'verbose_name_plural': 'Hero Banners (Home Page)'},
        ),
        migrations.AlterModelOptions(
            name='irishclubgrid',
            options={'verbose_name': '**New in Irish Club : Home Page (Add up to 6 Images of Products in Irish Club Here)', 'verbose_name_plural': '**New in Irish Club : Home Page (Add up to 6 Images of Products in Irish Club Here)'},
        ),
        migrations.AlterModelOptions(
            name='jackmillergrid',
            options={'verbose_name': '**New in Jack Miller : Home Page (Add up to 6 Images of Products in Jack Miller Here)', 'verbose_name_plural': '**New in Jack Miller : Home Page (Add up to 6 Images of Products in Jack Miller Here)'},
        ),
        migrations.AlterModelOptions(
            name='loopygrid',
            options={'verbose_name': '**New in Loopy : Home Page (Add up to 6 Images of Products in Loopy Here)', 'verbose_name_plural': '**New in Loopy : Home Page (Add up to 6 Images of Products in Loopy Here)'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Products (Add Your Products Here)', 'verbose_name_plural': 'Products (Add Your Products Here)'},
        ),
        migrations.AlterModelOptions(
            name='producthero',
            options={'verbose_name': '**Products - Hero Image (Products Page)', 'verbose_name_plural': '**Products - Hero Image (Products Page)'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store Locations : Home Screen (Add Your Store Details)', 'verbose_name_plural': 'Store Locations : Home Screen (Add Your Store Details)'},
        ),
        migrations.AlterModelOptions(
            name='storehero',
            options={'verbose_name': '**Our Stores - Hero Image (Our Stores Page)', 'verbose_name_plural': '**Our Stores - Hero Image (Our Stores Page)'},
        ),
        migrations.AlterModelOptions(
            name='updatebanner1',
            options={'verbose_name': 'Offers/Updates-1 (Add Any Offers/Updates to display on home screen - layer 1)', 'verbose_name_plural': 'Offers/Updates-1 (Add Any Offers/Updates to display on home screen - layer 1)'},
        ),
        migrations.AlterModelOptions(
            name='updatebanner2',
            options={'verbose_name': 'Offers/Updates-2 (Add Any Offers/Updates to display on home screen - layer 2)', 'verbose_name_plural': 'Offers/Updates-2 (Add Any Offers/Updates to display on home screen - layer 2)'},
        ),
        migrations.AlterModelOptions(
            name='updatebanner3',
            options={'verbose_name': 'Offers/Updates-3 (Add Any Offers/Updates to display on home screen - layer 3)', 'verbose_name_plural': 'Offers/Updates-3 (Add Any Offers/Updates to display on home screen - layer 3)'},
        ),
        migrations.AddField(
            model_name='product',
            name='made',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
